const quadros=[
{nome:'Flores', ano: '????',link:'quadros/quadro_44.jpg', wid: '304', heig: '236', posse: ' Carlos Roberto Guimarães e Silva e Maria Helena Angelini Guimarães Silva'},
{nome: 'Vaso 1', ano: '????', link:'quadros/quadro_45.jpg', wid: '304', heig: '236', posse: 'Carlos Roberto Guimarães e Silva e Maria Helena Angelini Guimarães Silva'},
{nome: 'Vaso 2', ano: '????', link:'quadros/quadro_46.jpg', wid: '304', heig: '236', posse: 'Carlos Roberto Guimarães e Silva e Maria Helena Angelini Guimarães Silva'},
{nome: 'Igreja e casarão', ano: '1974', link:'quadros/quadro_38.jpg', wid: '304', heig: '236', posse: 'Carlos Roberto Guimarães e Silva e Maria Helena Angelini Guimarães Silva'},
{nome: 'Mangas', ano: '1981', link:'quadros/quadro_39.jpg', wid: '304', heig: '236', posse: 'Carlos Roberto Guimarães e Silva e Maria Helena Angelini Guimarães Silva'},
{nome: 'Pimentões', ano: '1982', link:'quadros/quadro_40.jpg', wid: '304', heig: '236' , posse: ' Carlos Roberto Guimarães e Silva e Maria Helena Angelini Guimarães Silva'},
{nome: 'Milho', ano: '1982', link:'quadros/quadro_41.jpg', wid: '304', heig: '236', posse: ' Carlos Roberto Guimarães e Silva e Maria Helena Angelini Guimarães Silva'},
{nome: 'Mexericas', ano: '1982', link:'quadros/quadro_42.jpg', wid: '304', heig: '236', posse: 'Carlos Roberto Guimarães e Silva e Maria Helena Angelini Guimarães Silva'},
{nome: 'Margaridas', ano: '1982', link:'quadros/quadro_43.jpg', wid:'236', heig: '304', posse: 'Carlos Roberto Guimarães e Silva e Maria Helena Angelini Guimarães Silva'},
{nome: 'Hortências',ano: '1983', link:'quadros/quadro_36.jpg', wid: '304', heig: '236', posse: 'José de Jesus Soares e Maria Cristina Pazzianotto Soares'},
{nome: 'Carlos - filho', ano: '1984', link:'quadros/quadro_22.jpg', wid: '184', heig: '156', posse: 'Carlos Benjamim Pazzianotto e Leonice R Quibáo Pazzianotto'},
{nome: 'Olaria', ano: '1989', link:'quadros/quadro_13.jpg', wid: '304', heig: '236', posse: 'Carlos Benjamim Pazzianotto e Leonice R Quibáo Pazzianotto'},
{nome: 'Igrejinha', ano: '1989', link:'quadros/quadro_21.jpg', wid: '304', heig: '236', posse: 'Carlos Benjamim Pazzianotto e Leonice R Quibáo Pazzianotto'},
{nome: 'Curva na estrada', ano: '1989', link:'quadros/quadro_20.jpg', wid:'236', heig: '304', posse: 'Carlos Benjamim Pazzianotto e Leonice R Quibáo Pazzianotto'},
{nome: 'Árvore em beira de rio', ano: '1989', link:'quadros/quadro_23.jpg', wid: '236', heig: '304', posse: 'Maria Helena Bresciani Pazzianotto'},
{nome: 'Reflexos', ano: '1990', link:'quadros/quadro_12.jpg', wid: '304', heig: '236', posse: 'Carlos Benjamim Pazzianotto e Leonice R Quibáo Pazzianotto'},
{nome: 'Amigo Luiz', ano: '1990', link:'quadros/quadro_19.jpg', wid:'236', heig: '304', posse: 'Carlos Benjamim Pazzianotto e Leonice R Quibáo Pazzianotto'},
{nome: 'Casa', ano: '1991', link:'quadros/quadro_15.jpg', wid: '304', heig: '236', posse: 'Carlos Benjamim Pazzianotto e Leonice R Quibáo Pazzianotto'},
{nome: 'Casa no sítio', ano: '1991', link:'quadros/quadro_16.jpg', wid: '304', heig: '236', posse: 'Carlos Benjamim Pazzianotto e Leonice R Quibáo Pazzianotto'},
{nome: 'Flores', ano: '1991', link:'quadros/quadro_25.jpg', wid: '304', heig: '236', posse: 'Marcos Stein Jr e Cibele Aparecida Pazzianotto'},
{nome: 'Rosas', ano: '1993', link:'quadros/quadro_24.jpg', wid: '236', heig: '304', posse: 'Maria Helena Besciani Pazzianotto'},
{nome: 'Ponte do Santouro', ano: '1994', link:'quadros/quadro_11.jpg', wid: '304', heig: '236', posse: 'Carlos Benjamim Pazzianotto e Leonice R Quibáo Pazzianotto'},
{nome: 'Rua da Barra', ano: '1995', link:'quadros/quadro_33.jpg', wid: '304', heig: '236', posse: 'José de Jesus Soares e Maria Cristina Pazzianotto Soares'},
{nome: 'Cadeira', ano: '1996', link:'quadros/quadro_9.jpg', wid: '236', heig: '304', posse: 'José de Jesus Soares e Maria Cristina Pazzianotto Soares'},
{nome: 'Peixes', ano: '1996', link:'quadros/quadro_14.jpg', wid: '304', heig: '236', posse: 'Carlos Benjamim Pazzianotto e Leonice R Quibáo Pazzianotto'},
{nome: 'Beira de Rio', ano: '1997', link:'quadros/quadro_34.jpg', wid:'236', heig: '304', posse: 'Antonio Cláudio Campache'},
{nome: 'Natureza morta', ano: '1997', link:'quadros/quadro_35.jpg', wid: '304', heig: '236', posse: 'Antonio Cláudio Campache'},
{nome: 'Estação', ano: '1998', link:'quadros/quadro_2.jpg', wid: '304', heig: '236', posse: 'Hermes Bisin Jr. e Linéia O Quibáo Bisin'},
{nome: 'Barco', ano: '2000', link:'quadros/quadro_10.jpg', wid: '304', heig: '236', posse: 'Marcos Stein Jr. e Cibele Aparecida Pazzianotto'},
{nome: 'Igreja de Sete Fogões', ano: '2000', link:'quadros/quadro_26.jpeg', wid: '304', heig: '236', posse: 'Roberto Carlos Daroz e Lucimara Quibáo Daroz'},
{nome: 'Capivari Clube - Sede Social', ano: '2001', link:'quadros/quadro_5.jpg', wid: '304', heig: '236', posse: 'Capivari Clube Capivari'},
{nome: 'Capivari Clube - Sede Social', ano: '2001', link:'quadros/quadro_6.jpg', wid: '304', heig: '236', posse: 'Capivari Clube Capivari'},
{nome: 'Caipira picando fumo', ano: '2001', link:'quadros/quadro_17.jpg', wid:'236', heig: '304', posse: 'Carlos Benjamim Pazzianotto e Leonice R Quibáo Pazzianotto'},
{nome: 'Fim de tarde', ano: '2005', link:'quadros/quadro_18.jpg', wid: '304', heig: '236', posse: 'Carlos Benjamim Pazzianotto e Leonice R Quibáo Pazzianotto'},
{nome: 'O violeiro', ano: '2006', link:'quadros/quadro_4.jpg', wid: '304', heig: '236', posse: 'Marcos Stein Jr e Cibele Aparecida Pazzianotto''},
{nome: 'A estrada', ano: '2007', link:'quadros/quadro_1.jpg', wid:'236', heig: '304', posse: 'Hermes Bisin Jr. e Linéia O Quibáo Bisin'},
{nome: 'Encontro do Divino', ano: '????', link:'quadros/quadro_3.jpg', wid: '304', heig: '236', posse: 'José de Jesus Soares e Maria Cristina Pazzianotto Soares'},
{nome: 'Regente Feijó x Saldanha Marinho', ano: '1984', link:'quadros/quadro_7.jpg', wid: '304', heig: '236', posse: 'Maria de Lourdes Amaral Nogueira'},
{nome: 'Rua XV de Novembro', ano: '????', link:'quadros/quadro_8.jpg', wid: '304', heig: '236', posse: '???? '},
{nome: 'Estação Sorocabana', ano: '????', link:'quadros/quadro_27.jpg', wid: '304', heig: '236', posse: 'Alcides Gatti e Brandina Rodrigues Gatti'},
{nome: 'Mamão', ano: '????', link:'quadros/quadro_28.jpg', wid: '304', heig: '236', posse: '???? '},
{nome: 'Igrejinha', ano: '????', link:'quadros/quadro_29.jpg', wid: '236', heig: '304', posse: '???? '},
{nome: 'Casas velhas', ano: '????', link:'quadros/quadro_30.jpg', wid: '304', heig: '236', posse: '???? '},
{nome: 'Pescadores',ano: '1998', link:'quadros/quadro_37.jpg', wid: '304', heig: '236', posse: 'José de Jesus Soares e Maria Cristina Pazzianotto Soares'},
{nome: 'Pescadores', ano: '1979', link:'quadros/quadro_32.jpg', wid: '304', heig: '236', posse: ' Walmor Val'},
{nome: 'Pescador limpando o peixe', ano: '1993', link:'quadros/quadro_47.jpg', wid: '304', heig: '236', posse: '???? '},
{nome: 'Usina Açucareira Santa Cruz', ano: '1983', link:'quadros/quadro_48.jpg', wid: '304', heig: '236', posse: ' Orlando Carniceli Jr.'},
{nome: 'Represa de Santa Rita', ano: '1996', link:'quadros/quadro_49.jpg', wid: '304', heig: '236', posse: 'Carlos Benjamim Pazzianotto e Leonice R Quibáo Pazzianotto'},
{nome: 'Sítio', ano: '2009', link:'quadros/quadro_50.jpg', wid: '304', heig: '236', posse: ' Carlos Benjamim Pazzianotto'},
{nome: 'Natureza morta', ano: '1983', link:'quadros/quadro_52.png', wid: '304', heig: '236', posse: 'Maria Adelia Teixeira Da Silva Matias'},
{nome: 'Praça', ano: '1985', link:'quadros/quadro_53.jpg', wid: '304', heig: '236', posse: ' Museu Histórico Dr Cesário Motta Júnior Capivari'},
{nome: 'Casa sítio', ano: '1985', link:'quadros/quadro_54.jpg', wid: '304', heig: '236', posse: 'Pedro Forner'},
{nome: 'Casa do Gilson',ano: '1992', link:'quadros/quadro_55.jpg', wid: '304', heig: '236', posse: 'Gilson Christófoli'},
{nome: 'Casa de pescador', ano: '1981', link:'quadros/quadro_56.jpg', wid: '304', heig: '236', posse: 'Pedro Forner'},
{nome: 'Casa no sítio', ano: '1988', link:'quadros/quadro_57.jpg', wid: '304', heig: '236', posse: 'Gilson Christófoli'},
{nome: 'Cortume', ano: '????', link:'quadros/quadro_58.jpg', wid: '304', heig: '236', posse: 'Pedro Forner'},
{nome: 'Milho verde',  ano: '????', link:'quadros/quadro_59.jpg', wid: '304', heig: '236', posse: 'Pedro Forner'},
{nome: 'Rua XV', ano: '1984', link:'quadros/quadro_60.jpg', wid: '304', heig: '236', posse: 'Pedro Forner'}
];

//export default quadros;

